from __future__ import annotations


HARDCOVER_DEFAULT_USER_AGENT = "hardcover-calibre-audit/2026.04 (personal library audit)"
CACHE_FILENAME = "hardcover_cache.sqlite"
LEGACY_CACHE_FILENAME = "hardcover_cache.json"
DEFAULT_CACHE_TTL_HOURS = 1440.0
DEFAULT_SEARCH_CACHE_TTL_HOURS = 720.0
DEFAULT_EMPTY_CACHE_TTL_HOURS = 168.0
DEFAULT_EDITION_CACHE_TTL_HOURS = 720.0
DEFAULT_PROGRESS_EVERY = 25


__all__ = [
    "HARDCOVER_DEFAULT_USER_AGENT",
    "CACHE_FILENAME",
    "LEGACY_CACHE_FILENAME",
    "DEFAULT_CACHE_TTL_HOURS",
    "DEFAULT_SEARCH_CACHE_TTL_HOURS",
    "DEFAULT_EMPTY_CACHE_TTL_HOURS",
    "DEFAULT_EDITION_CACHE_TTL_HOURS",
    "DEFAULT_PROGRESS_EVERY",
]
